# Generated by Django 4.0.2 on 2022-04-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0017_trackedposts'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedposts',
            name='view_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='trackedposts',
            name='ip',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
