# Generated by Django 4.0.2 on 2022-04-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0018_trackedposts_view_count_alter_trackedposts_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackedposts',
            name='view_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
