# Generated by Django 4.0.2 on 2022-04-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0019_alter_trackedposts_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackedposts',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
