# Generated by Django 4.0.2 on 2022-04-05 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0021_alter_trackedposts_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackedposts',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracker', to='questions.question'),
        ),
    ]
