# Generated by Django 4.0.2 on 2022-04-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0022_alter_trackedposts_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trackedposts',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='trackedposts',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='trackedposts',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
