# Generated by Django 4.0.2 on 2022-04-06 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0024_remove_question_view_count'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrackedPosts',
            new_name='TrackedPost',
        ),
    ]
