# Generated by Django 4.0.2 on 2022-04-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportedissue',
            name='issue_in_detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
